# Generated by Django 4.2.5 on 2023-09-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(editable=False)),
                ('modified_on', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('lifespan', models.IntegerField(null=True)),
                ('oxygen', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
