# Generated by Django 4.2.5 on 2023-09-09 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_rename_treetypes_treetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(editable=False)),
                ('modified_on', models.DateTimeField(editable=False)),
                ('identifier', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('planted_on', models.DateField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.treetype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
