# Generated by Django 4.2.5 on 2023-09-09 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree', '0006_rename_treerecords_treerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='last_viewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_last_viewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tree',
            name='last_viewed_on',
            field=models.DateTimeField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treerecord',
            name='last_viewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_last_viewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treerecord',
            name='last_viewed_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treetype',
            name='last_viewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_last_viewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treetype',
            name='last_viewed_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
