# Generated by Django 4.2.5 on 2023-09-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0008_treerecord_set_alart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treerecord',
            old_name='is_cutted',
            new_name='is_cut',
        ),
    ]
